require(MASS)
require(ggplot2)
set.seed(52771)

# Generate Scenario One Green Test Data
s1test.green <- mvrnorm(n=500,mu=c(2,1),Sigma=diag(2))
s1test.green<- data.frame(s1test.green)
#colnames(s1test.green) <- c('x','y')
s1test.green$Class <- 1

# Generate Scenario One Green Training Data
s1train.green <- mvrnorm(n=100,mu=c(2,1),Sigma=diag(2))
s1train.green<- data.frame(s1train.green)
#colnames(s1train.green) <- c('x','y')
s1train.green$Class <- 1

#Generate Scenario One Red Test Data
s1test.red <- mvrnorm(n=500,mu=c(1,2),Sigma=diag(2))
s1test.red<- data.frame(s1test.red)
#colnames(s1test.red) <- c('x','y')
s1test.red$Class <- 0

#Generate Scenario One Red Training Data
s1train.red <- mvrnorm(n=100,mu=c(1,2),Sigma=diag(2))
s1train.red<- data.frame(s1train.red)
#colnames(s1train.red) <- c('x','y')
s1train.red$Class <- 0

# Create a data frames for Scenario 1 testing and training data
scenario.1.test <- rbind(s1test.green,s1test.red)
scenario.1.train <- rbind(s1train.green,s1train.red)

# Add columns for the Bayes Rule and the Linear model to both testing and training data
# The Bayes Rule assigns Class = 1 if X1 > X2, Otherwise Class = 0
# The Linear Model assigns Class = 1 if .1606*X1 - .2039*X2 + .5762 > 0.5, else Class = 0
# This assumes the seed 52771, but the code will handle changes in seed.
# The linear Model is generated by lm(Class~X1+X2,data=scenario.1.train)
lin1 <- coef(lm(Class~X1+X2,data=scenario.1.train))
scenario.1.test$Bayes.mod <- apply(scenario.1.test,1,function(row) ifelse(row[1] > row[2],1,0))
scenario.1.train$Bayes.mod <- apply(scenario.1.train,1,function(row) ifelse(row[1] > row[2],1,0))
scenario.1.test$Lin.mod <- apply(scenario.1.test,1,function(row) ifelse(lin1[2]*row[1]+lin1[3]*row[2]+lin1[1] > 0.5,1,0))
scenario.1.train$Lin.mod <- apply(scenario.1.train,1,function(row) ifelse(lin1[2]*row[1]+lin1[3]*row[2]+lin1[1] > 0.5,1,0))
#scenario.1.train$Lin.mod <- apply(scenario.1.train,1,function(row) ifelse(.1606*row[1]-.2039*row[2]+.5762 > 0.5,1,0))

# Add columns containing 1 if the model is in error, and 0 if it is not. The mean of these columns is the error for each model
scenario.1.test$Bayes.error <- apply(scenario.1.test,1,function(row) ifelse(row[3] != row[4],1,0))
scenario.1.train$Bayes.error <- apply(scenario.1.train,1,function(row) ifelse(row[3] != row[4],1,0))
scenario.1.test$Lin.error <- apply(scenario.1.test,1,function(row) ifelse(row[3] != row[5],1,0))
scenario.1.train$Lin.error <- apply(scenario.1.train,1,function(row) ifelse(row[3] != row[5],1,0))

#Calculate testing and train errors for Bayes and Linear models in the testing and training data for Scenario 1
sc1.Bayes.test.error <- mean(scenario.1.test$Bayes.error)
sc1.Bayes.train.error <- mean(scenario.1.train$Bayes.error)
sc1.Lin.test.error <- mean(scenario.1.test$Lin.error)
sc1.Lin.train.error <- mean(scenario.1.train$Lin.error)


# Generate Scenario Two Means
green.means <- mvrnorm(n=10,mu=c(1,0),Sigma=diag(2))
red.means <- mvrnorm(n=10,mu=c(0,1),Sigma=diag(2))

# Create matrix for Scenario Two
# Red Training class
s2test.red <- t(replicate(500,{muk <- red.means[sample(1:10,1),];mvrnorm(1,mu=muk,Sigma=(diag(2)/5))}))
s2test.red <- data.frame(s2test.red)
#colnames(s2test.red) <- c('x','y')
s2test.red$Class <- 0

# Create matrix for Scenario Two
# Red Training class
s2train.red <- t(replicate(100,{muk <- red.means[sample(1:10,1),];mvrnorm(1,mu=muk,Sigma=(diag(2)/5))}))
s2train.red <- data.frame(s2train.red)
#colnames(s2train.red) <- c('x','y')
s2train.red$Class <- 0

# Create matrix for Scenario Two
# Green Test class
s2test.green <- t(replicate(500,{muk <- green.means[sample(1:10,1),];mvrnorm(1,mu=muk,Sigma=(diag(2)/5))}))
s2test.green <- data.frame(s2test.green)
#colnames(s2test.green) <- c('x','y')
s2test.green$Class <- 1

# Create matrix for Scenario Two
# Green Training class
s2train.green <- t(replicate(100,{muk <- green.means[sample(1:10,1),];mvrnorm(1,mu=muk,Sigma=(diag(2)/5))}))
s2train.green <- data.frame(s2train.green)
#colnames(s2train.green) <- c('x','y')
s2train.green$Class <- 1

# Create Scenario Two test and training data frames
scenario.2.test <- rbind(s2test.green,s2test.red)
scenario.2.train <- rbind(s2train.green,s2train.red)

# Add columns for the Linear model to both testing and training data
# The Linear Model assigns Class = 1 if .27892*X1 - .06001*X2 + .36129 > 0.5, else Class = 0
# The linear Model is generated by lm(Class~X1+X2,data=scenario.2.train)
# This assumes Seed 52771 but the code will handle a change in seed
lin2 <- coef(lm(Class~X1+X2,data=scenario.2.train))
scenario.2.test$Lin.mod <- apply(scenario.2.test,1,function(row) ifelse(lin2[2]*row[1]-lin2[3]*row[2]+lin2[1] > 0.5,1,0))
scenario.2.train$Lin.mod <- apply(scenario.2.train,1,function(row) ifelse(lin2[2]*row[1]-lin2[3]*row[2]+lin2[1] > 0.5,1,0))

# Add columns containing 1 if the model is in error, and 0 if it is not. The mean of these columns is the error for each model
scenario.2.test$Lin.error <- apply(scenario.2.test,1,function(row) ifelse(row[3] != row[4],1,0))
scenario.2.train$Lin.error <- apply(scenario.2.train,1,function(row) ifelse(row[3] != row[4],1,0))

#Calculate testing and train errors for Bayes and Linear models in the testing and training data for Scenario 1
sc2.Lin.test.error <- mean(scenario.2.test$Lin.error)
sc2.Lin.train.error <- mean(scenario.2.train$Lin.error)

# Code to generate
plot.scenario.1 <- function(){
  p <- ggplot(scenario.1.train,aes(X1,X2))
  p <- p + geom_point(aes(colour=as.factor(Class)),pch=1,size=4)
  p <- p + scale_colour_manual(values=c('Red','Green4'),name="Class",labels=c("Red","Green"))
  p <- p + geom_abline(intercept=0,slope=1,color='Blue',name='Bayes Boundary')
  p <- p + geom_abline(intercept=((lin1[1]-.5)/-lin1[3]),slope=(lin1[2]/-lin1[3]),color='Blue',lty=5)
  p <- p + ggtitle('Scenario 1')
  p <- p + theme_bw()
  return(p)
}
plot.scenario.2 <- function(){
  p <- ggplot(scenario.2.train,aes(X1,X2))
  p <- p + geom_point(aes(colour=as.factor(Class)),pch=1,size=4)
  p <- p + geom_abline(intercept=((lin2[1]-.5)/-lin2[3]),slope=(lin2[2]/-lin2[3]),color='Blue',lty=5)
  p <- p + scale_colour_manual(values=c('Red','Green4'),name="Class",labels=c("Red","Green"))
  p <- p + ggtitle('Scenario 2')
  p <- p + theme_bw()
  return(p)
}